[package]
name = "cargo-runner"
version = "0.1.0"
authors = ["Diana"]
edition = "2018"


[dependencies]
structopt = "0.3.0"
serde = { version = "1.0.99", features = ["derive"] }
cargo_metadata = "0.8.2"
serde_json = "1.0.40"
